### ISSUE TITLE
[enhancement] Support for alternative translations of a chosen term?

### ISSUE THREAD

**Issue by benthamite** [tmalsburg/txl.el#2]
Thank you for creating this great package. Have you considered adding support for alternative translations of a given term (i.e. the list of words that show up when one clicks on a term on the web or desktop app)?

**Comment by tmalsburg** [comment]
Hi, glad you like it.
> Have you considered adding support for alternative translations

No, I haven't, and I'm not sure the API supports that. It's a good idea, but it seems like a bigger feature (especially with respect to the UI implementation) and I won't have time to work on that.  Feel free to make a PR if you'd like to work on it.
