### ISSUE TITLE
Publish on MELPA?

### ISSUE THREAD

**Issue by jman-schief** [tmalsburg/txl.el#3]
Hi,

in the README I read "TXL is not _yet_ available on MELPA or similar repositories". That somehow hints at the intent to do at some point? Being the package stable (I use with `straight` since long), would you evaluate publishing it? So that people can pull it without asking github (or keeping an offline copy).

thanks for considering this question and thanks for the package itself.

**Comment by tmalsburg** [comment]
Submitted it.  See here:
https://github.com/melpa/melpa/pull/9155

**Comment by tmalsburg** [comment]
Done: https://melpa.org/#/txl

**Comment by jman-schief** [comment]
vielen lieben Dank :)
