### ISSUE TITLE
Easily translate in the other direction than specified by `txl-languages`

### ISSUE THREAD

**Issue by dbitouze** [tmalsburg/txl.el#4]
Thanks for this package!

It would be nice if we could easily translate in the other direction than specified by `txl-languages`. For example, with `(setq txl-languages '(FR . EN-US))`, I'd like to be able to easily translate from EN-US to FR. At first glance from the documentation, I thought the prefix argument (`C-u`) served this purpose, but `C-u C-x t` doesn't give the expected result (it still translates from FR to EN-US).

**Comment by tmalsburg** [comment]
Please read the “usage” section on the main page of this repo. If you think there is a bug, it would be great if you could provide a reproducible example. Thank you.

**Comment by dbitouze** [comment]
Ah, after some experiments, I understand better now. Sorry for the noise.

**Comment by tmalsburg** [comment]
If a paragraph doesn't have enough text, guess-language may guess incorrectly and then the translation is not what you'd expect.  And some language pairs can be guessed more reliably than others.
